### ISSUE TITLE
wrong link to repo in README.md

### ISSUE THREAD

**Issue by ffutlapuztar** [Stability-AI/webui-stability-api#1]
"In the Extensions > Install from URL tab, paste: https://github.com/Stability-AI/webui-stability"

should be "https://github.com/Stability-AI/webui-stability-api" I think.

Beside that little mistyping it works very nice! ;-)

Thank you!

**Comment by Klace** [comment]
Whoops! Got lost in the formatting! 🙃 

Corrected! 

Thank you!
